name: Test SuperAgent Zero Installation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-installation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Git
      run: |
        sudo apt-get update
        sudo apt-get install -y git
    
    - name: Test install.sh execution
      run: |
        # Test that install.sh runs without errors
        chmod +x install.sh
        # Dry run test (don't actually install globally in CI)
        bash -n install.sh
        echo "✅ install.sh syntax check passed"
    
    - name: Test setup.sh execution  
      run: |
        # Test that setup.sh runs without errors
        chmod +x setup.sh
        # Dry run test  
        bash -n setup.sh
        echo "✅ setup.sh syntax check passed"
    
    - name: Validate framework structure
      run: |
        # Check required directories exist
        test -d agents || (echo "❌ agents missing" && exit 1)
        test -d agents/agent-00-command || (echo "❌ agent-00-command missing" && exit 1)
        test -d mcp-configs || (echo "❌ mcp-configs missing" && exit 1)
        test -d examples || (echo "❌ examples missing" && exit 1)
        test -d bin || (echo "❌ bin missing" && exit 1)
        
        # Check required files exist
        test -f README.md || (echo "❌ README.md missing" && exit 1)
        test -f QUICKSTART.md || (echo "❌ QUICKSTART.md missing" && exit 1)
        test -f LICENSE || (echo "❌ LICENSE missing" && exit 1)
        test -f CONTRIBUTING.md || (echo "❌ CONTRIBUTING.md missing" && exit 1)
        test -f VERSION || (echo "❌ VERSION missing" && exit 1)
        test -f .gitignore || (echo "❌ .gitignore missing" && exit 1)
        test -f .gitattributes || (echo "❌ .gitattributes missing" && exit 1)
        
        echo "✅ Framework structure validation passed"
    
    - name: Test documentation links
      run: |
        # Basic check that internal documentation links are valid
        grep -r "claude-initialization.md" . --include="*.md" || echo "No claude-initialization references found"
        grep -r "Agent-Creation-Templates.md" . --include="*.md" || echo "No agent template references found"
        echo "✅ Documentation link check completed"
    
    - name: Test example structure
      run: |
        # Verify examples have required structure
        test -f examples/app-development/README.md || (echo "❌ App development examples missing" && exit 1)
        test -f examples/business-intelligence/README.md || (echo "❌ Business intelligence examples missing" && exit 1)
        test -f examples/academic-research/README.md || (echo "❌ Academic research examples missing" && exit 1)
        test -f examples/legal-analysis/README.md || (echo "❌ Legal analysis examples missing" && exit 1)
        
        echo "✅ Example structure validation passed"

    - name: Test agent framework
      run: |
        # Verify agent framework files exist and are properly formatted
        test -f agents/agent-00-command/Agent-0-Command-Center.md || (echo "❌ Agent 0 Command Center missing" && exit 1)
        test -f agents/agent-00-command/Agent-Creation-Templates.md || (echo "❌ Agent Creation Templates missing" && exit 1)
        test -f agents/agent-00-command/Memory-and-Strategy.md || (echo "❌ Memory and Strategy missing" && exit 1)
        
        # Check agent files have required sections
        grep -q "## Agent Selection Guide" agents/agent-00-command/Agent-0-Command-Center.md || (echo "❌ Command Center missing core sections" && exit 1)
        grep -q "## Pre-Built Agent Types" agents/agent-00-command/Agent-Creation-Templates.md || (echo "❌ Templates missing core sections" && exit 1)
        
        # Test utility scripts
        test -f bin/update.sh || (echo "❌ Update script missing" && exit 1)
        test -f bin/validate.sh || (echo "❌ Validate script missing" && exit 1)
        test -x bin/update.sh || (echo "❌ Update script not executable" && exit 1)
        test -x bin/validate.sh || (echo "❌ Validate script not executable" && exit 1)
        
        echo "✅ Agent framework validation passed"

  test-scripts:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Test on macOS
      run: |
        chmod +x install.sh setup.sh
        
        # Test script syntax
        bash -n install.sh
        bash -n setup.sh
        
        echo "✅ macOS script validation passed"